
#Region " Option Statements "

Option Strict On
Option Explicit On
Option Infer Off

#End Region

#Region " Imports "

Imports System.IO

#End Region

#Region " AppGlobals "
''' <summary>
''' Provides global application definitions.
''' </summary>
Friend Module AppGlobals

    ''' <summary>
    ''' The directory path for storing temporary MUI files for pending operations.
    ''' </summary>
    Friend ReadOnly BaseTempMuiDirectoryPath As String =
        Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), $"{My.Application.Info.ProductName}")

    ''' <summary>
    ''' Full file path to the Sysinternals <b>MoveFile</b> executable (dynamically selected as either 
    ''' 32-bit or 64-bit based on the current system architecture) used to schedule file replacements 
    ''' that will be executed by the Windows Session Manager upon the next system restart.
    ''' </summary>
    Friend ReadOnly MOVEFILE_EXEC_PATH As String =
        If(IntPtr.Size = 8,
           Path.Combine(My.Application.Info.DirectoryPath, "Tools", "movefile64.exe"),
           Path.Combine(My.Application.Info.DirectoryPath, "Tools", "movefile.exe"))

    ''' <summary>
    ''' Full file path to the <b>ResourceHacker</b> executable used to modify the <c>Accelerators</c> table on MUI files.
    ''' <para></para>
    ''' Resource Hacker website: <see href="https://www.angusj.com/resourcehacker/"/>
    ''' </summary>
    Friend ReadOnly RESOURCE_HACKER_EXEC_PATH As String =
        Path.Combine(My.Application.Info.DirectoryPath, "Tools", "ResourceHacker.exe")

    ''' <summary>
    ''' Full path to the log file generated by a call to <b>ResourceHacker</b> executable.
    ''' <para></para>
    ''' Movefile website: <see href="https://learn.microsoft.com/sysinternals/downloads/pendmoves?utm_source=chatgpt.com#movefile-usage"/>
    ''' </summary>
    Friend ReadOnly RESOURCE_HACKER_LOGFILE_PATH As String =
        Path.Combine(Path.GetTempPath(), "ResourceHacker.log")

    ''' <summary>
    ''' The file extension suffix used to create backup copies of original MUI 
    ''' files scheduled to occur upon the next system reboot.
    ''' </summary>
    Friend Const MuiFileBackupSuffix As String = "bak"

    ''' <summary>
    ''' The file extension suffix used for pending file replacement operations 
    ''' scheduled to occur upon the next system reboot.
    ''' </summary>
    Friend Const MuiFilePendingSuffix As String = "pending"

    ''' <summary>
    ''' The file extension suffix used to set distinguish files that failed 
    ''' during the scheduled file replacement operation.
    ''' </summary>
    Friend Const MuiFileFailedSuffix As String = "failed"

End Module

#End Region
