
#Region " Option Statements "

Option Strict On
Option Explicit On
Option Infer Off

#End Region

#Region " AccTables "

''' <summary>
''' Provides MUI accelerator table definitions.
''' </summary>
Friend Module AccTables

#Region " Accelerator Table strings to Englishize es-ES MUI files "

    ' NOTE: The "esES" naming in CONST member names indicates they are linked to an es-ES MUI accelerator table.
    '       These tables applies en-US shortcuts; they do NOT apply es-ES shortcuts.

#Region " shell32.dll.mui "

#Region " Windows 10 variants "

    ''' <summary>
    ''' Accelerator table definition for <c>shell32.dll.mui</c> with CRC32: fb5e8156
    ''' </summary>
    Friend Const SHELL32_esES_ENGLISHIZED_fb5e8156 As String = "
LANGUAGE LANG_NEUTRAL, SUBLANG_NEUTRAL


1 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_Z, 28699, NOINVERT, CONTROL, VIRTKEY
    VK_Y, 28704, NOINVERT, CONTROL, VIRTKEY
    VK_X, 28696, NOINVERT, CONTROL, VIRTKEY
    VK_C, 28697, NOINVERT, CONTROL, VIRTKEY
    VK_V, 28698, NOINVERT, CONTROL, VIRTKEY
    VK_A, 28705, NOINVERT, CONTROL, VIRTKEY
    VK_N, 28933, NOINVERT, CONTROL, VIRTKEY
    VK_T, 28935, NOINVERT, CONTROL, VIRTKEY
    VK_F1, 28817, NOINVERT, VIRTKEY
    VK_F2, 28690, NOINVERT, VIRTKEY
    VK_INSERT, 28697, NOINVERT, CONTROL, VIRTKEY
    VK_INSERT, 28698, NOINVERT, SHIFT, VIRTKEY
    VK_DELETE, 28689, NOINVERT, VIRTKEY
    VK_D, 28689, NOINVERT, CONTROL, VIRTKEY
    VK_DELETE, 28689, NOINVERT, SHIFT, VIRTKEY
    VK_RETURN, 28691, NOINVERT, ALT, VIRTKEY
    VK_1, 28749, ALT, CONTROL, VIRTKEY
    VK_2, 28751, ALT, CONTROL, VIRTKEY
    VK_3, 28750, ALT, CONTROL, VIRTKEY
    VK_4, 28752, ALT, CONTROL, VIRTKEY
    VK_5, 28753, ALT, CONTROL, VIRTKEY
    VK_6, 28747, ALT, CONTROL, VIRTKEY
    VK_7, 28748, ALT, CONTROL, VIRTKEY
    VK_8, 28754, ALT, CONTROL, VIRTKEY
    VK_ADD, 28759, ALT, CONTROL, VIRTKEY
    VK_SUBTRACT, 28760, ALT, CONTROL, VIRTKEY
    VK_OEM_PLUS, 28759, ALT, CONTROL, VIRTKEY
    VK_OEM_MINUS, 28760, ALT, CONTROL, VIRTKEY
}


3 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    ""s"", 34172, ALT
    VK_TAB, 41008, NOINVERT, VIRTKEY
    VK_TAB, 41008, NOINVERT, SHIFT, VIRTKEY
    VK_F5, 41504, NOINVERT, VIRTKEY
    VK_F6, 41008, NOINVERT, VIRTKEY
    VK_F3, 41093, NOINVERT, VIRTKEY
    VK_F4, 40964, NOINVERT, ALT, VIRTKEY
    VK_N, 40999, NOINVERT, CONTROL, SHIFT, VIRTKEY
}


4 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_F5, 1, NOINVERT, VIRTKEY
    VK_BACK, 2, NOINVERT, VIRTKEY
    VK_BACK, 3, NOINVERT, CONTROL, VIRTKEY
    VK_E, 40998, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_N, 40999, NOINVERT, CONTROL, SHIFT, VIRTKEY
}


5 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_X, 41025, NOINVERT, CONTROL, VIRTKEY
    VK_C, 41026, NOINVERT, CONTROL, VIRTKEY
    VK_V, 41027, NOINVERT, CONTROL, VIRTKEY
    VK_F2, 40996, NOINVERT, VIRTKEY
    VK_INSERT, 41026, NOINVERT, CONTROL, VIRTKEY
    VK_INSERT, 41027, NOINVERT, SHIFT, VIRTKEY
    VK_DELETE, 40995, NOINVERT, VIRTKEY
    VK_DELETE, 40995, NOINVERT, SHIFT, VIRTKEY
    VK_D, 40995, NOINVERT, CONTROL, VIRTKEY
    VK_RETURN, 40997, NOINVERT, ALT, VIRTKEY
    VK_F5, 41504, NOINVERT, VIRTKEY
}

"

    ''' <summary>
    ''' Accelerator table definition for <c>shell32.dll.mui</c> with CRC32: 3600a388
    ''' </summary>
    Friend Const SHELL32_esES_ENGLISHIZED_3600a388 As String = "
LANGUAGE LANG_NEUTRAL, SUBLANG_NEUTRAL


1 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_Z, 28699, NOINVERT, CONTROL, VIRTKEY
    VK_Y, 28704, NOINVERT, CONTROL, VIRTKEY
    VK_X, 28696, NOINVERT, CONTROL, VIRTKEY
    VK_C, 28697, NOINVERT, CONTROL, VIRTKEY
    VK_V, 28698, NOINVERT, CONTROL, VIRTKEY
    VK_A, 28705, NOINVERT, CONTROL, VIRTKEY
    VK_N, 28933, NOINVERT, CONTROL, VIRTKEY
    VK_T, 28935, NOINVERT, CONTROL, VIRTKEY
    VK_F1, 28817, NOINVERT, VIRTKEY
    VK_F2, 28690, NOINVERT, VIRTKEY
    VK_INSERT, 28697, NOINVERT, CONTROL, VIRTKEY
    VK_INSERT, 28698, NOINVERT, SHIFT, VIRTKEY
    VK_DELETE, 28689, NOINVERT, VIRTKEY
    VK_D, 28689, NOINVERT, CONTROL, VIRTKEY
    VK_DELETE, 28689, NOINVERT, SHIFT, VIRTKEY
    VK_RETURN, 28691, NOINVERT, ALT, VIRTKEY
    VK_1, 28749, CONTROL, SHIFT, VIRTKEY
    VK_2, 28751, CONTROL, SHIFT, VIRTKEY
    VK_3, 28750, CONTROL, SHIFT, VIRTKEY
    VK_4, 28752, CONTROL, SHIFT, VIRTKEY
    VK_5, 28753, CONTROL, SHIFT, VIRTKEY
    VK_6, 28747, CONTROL, SHIFT, VIRTKEY
    VK_7, 28748, CONTROL, SHIFT, VIRTKEY
    VK_8, 28754, CONTROL, SHIFT, VIRTKEY
    VK_ADD, 28759, ALT, CONTROL, VIRTKEY
    VK_SUBTRACT, 28760, ALT, CONTROL, VIRTKEY
    VK_OEM_PLUS, 28759, ALT, CONTROL, VIRTKEY
    VK_OEM_MINUS, 28760, ALT, CONTROL, VIRTKEY
}


3 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    ""s"", 34172, ALT
    VK_TAB, 41008, NOINVERT, VIRTKEY
    VK_TAB, 41008, NOINVERT, SHIFT, VIRTKEY
    VK_F5, 41504, NOINVERT, VIRTKEY
    VK_F6, 41008, NOINVERT, VIRTKEY
    VK_F3, 41093, NOINVERT, VIRTKEY
    VK_F4, 40964, NOINVERT, ALT, VIRTKEY
    VK_N, 40999, NOINVERT, CONTROL, SHIFT, VIRTKEY
}


4 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_F5, 1, NOINVERT, VIRTKEY
    VK_BACK, 2, NOINVERT, VIRTKEY
    VK_BACK, 3, NOINVERT, CONTROL, VIRTKEY
    VK_E, 40998, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_N, 40999, NOINVERT, CONTROL, SHIFT, VIRTKEY
}


5 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_X, 41025, NOINVERT, CONTROL, VIRTKEY
    VK_C, 41026, NOINVERT, CONTROL, VIRTKEY
    VK_V, 41027, NOINVERT, CONTROL, VIRTKEY
    VK_F2, 40996, NOINVERT, VIRTKEY
    VK_INSERT, 41026, NOINVERT, CONTROL, VIRTKEY
    VK_INSERT, 41027, NOINVERT, SHIFT, VIRTKEY
    VK_DELETE, 40995, NOINVERT, VIRTKEY
    VK_DELETE, 40995, NOINVERT, SHIFT, VIRTKEY
    VK_D, 40995, NOINVERT, CONTROL, VIRTKEY
    VK_RETURN, 40997, NOINVERT, ALT, VIRTKEY
    VK_F5, 41504, NOINVERT, VIRTKEY
}

"

    ''' <summary>
    ''' Accelerator table definition for <c>shell32.dll.mui</c> with CRC32: 1f3defe7
    ''' </summary>
    Friend Const SHELL32_esES_ENGLISHIZED_1f3defe7 As String = "
LANGUAGE LANG_NEUTRAL, SUBLANG_NEUTRAL


1 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_Z, 28699, NOINVERT, CONTROL, VIRTKEY
    VK_Y, 28704, NOINVERT, CONTROL, VIRTKEY
    VK_X, 28696, NOINVERT, CONTROL, VIRTKEY
    VK_C, 28697, NOINVERT, CONTROL, VIRTKEY
    VK_V, 28698, NOINVERT, CONTROL, VIRTKEY
    VK_A, 28705, NOINVERT, CONTROL, VIRTKEY
    VK_N, 28933, NOINVERT, CONTROL, VIRTKEY
    VK_T, 28935, NOINVERT, CONTROL, VIRTKEY
    VK_F1, 28817, NOINVERT, VIRTKEY
    VK_F2, 28690, NOINVERT, VIRTKEY
    VK_INSERT, 28697, NOINVERT, CONTROL, VIRTKEY
    VK_INSERT, 28698, NOINVERT, SHIFT, VIRTKEY
    VK_DELETE, 28689, NOINVERT, VIRTKEY
    VK_D, 28689, NOINVERT, CONTROL, VIRTKEY
    VK_DELETE, 28689, NOINVERT, SHIFT, VIRTKEY
    VK_RETURN, 28691, NOINVERT, ALT, VIRTKEY
    VK_1, 28749, CONTROL, SHIFT, VIRTKEY
    VK_2, 28751, CONTROL, SHIFT, VIRTKEY
    VK_3, 28750, CONTROL, SHIFT, VIRTKEY
    VK_4, 28752, CONTROL, SHIFT, VIRTKEY
    VK_5, 28753, CONTROL, SHIFT, VIRTKEY
    VK_6, 28747, CONTROL, SHIFT, VIRTKEY
    VK_7, 28748, CONTROL, SHIFT, VIRTKEY
    VK_8, 28754, CONTROL, SHIFT, VIRTKEY
    VK_ADD, 28759, ALT, CONTROL, VIRTKEY
    VK_SUBTRACT, 28760, ALT, CONTROL, VIRTKEY
    VK_OEM_PLUS, 28759, ALT, CONTROL, VIRTKEY
    VK_OEM_MINUS, 28760, ALT, CONTROL, VIRTKEY
}


3 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    ""s"", 34172, ALT
    VK_TAB, 41008, NOINVERT, VIRTKEY
    VK_TAB, 41008, NOINVERT, SHIFT, VIRTKEY
    VK_F5, 41504, NOINVERT, VIRTKEY
    VK_F6, 41008, NOINVERT, VIRTKEY
    VK_F3, 41093, NOINVERT, VIRTKEY
    VK_F4, 40964, NOINVERT, ALT, VIRTKEY
    VK_N, 40999, NOINVERT, CONTROL, SHIFT, VIRTKEY
}


4 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_F5, 1, NOINVERT, VIRTKEY
    VK_BACK, 2, NOINVERT, VIRTKEY
    VK_BACK, 3, NOINVERT, CONTROL, VIRTKEY
    VK_E, 40998, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_N, 40999, NOINVERT, CONTROL, SHIFT, VIRTKEY
}


5 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_X, 41025, NOINVERT, CONTROL, VIRTKEY
    VK_C, 41026, NOINVERT, CONTROL, VIRTKEY
    VK_V, 41027, NOINVERT, CONTROL, VIRTKEY
    VK_F2, 40996, NOINVERT, VIRTKEY
    VK_INSERT, 41026, NOINVERT, CONTROL, VIRTKEY
    VK_INSERT, 41027, NOINVERT, SHIFT, VIRTKEY
    VK_DELETE, 40995, NOINVERT, VIRTKEY
    VK_DELETE, 40995, NOINVERT, SHIFT, VIRTKEY
    VK_D, 40995, NOINVERT, CONTROL, VIRTKEY
    VK_RETURN, 40997, NOINVERT, ALT, VIRTKEY
    VK_F5, 41504, NOINVERT, VIRTKEY
}

"

#End Region

#Region " Windows 11 variants "

    ''' <summary>
    ''' Accelerator table definition for <c>shell32.dll.mui</c> with CRC32: f7d515d8
    ''' </summary>
    Friend Const SHELL32_esES_ENGLISHIZED_f7d515d8 As String = "
LANGUAGE LANG_NEUTRAL, SUBLANG_NEUTRAL


1 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_Z, 28699, NOINVERT, CONTROL, VIRTKEY
    VK_Y, 28704, NOINVERT, CONTROL, VIRTKEY
    VK_X, 28696, NOINVERT, CONTROL, VIRTKEY
    VK_C, 28697, NOINVERT, CONTROL, VIRTKEY
    VK_C, 28705, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_V, 28698, NOINVERT, CONTROL, VIRTKEY
    VK_A, 28707, NOINVERT, CONTROL, VIRTKEY
    VK_N, 28933, NOINVERT, CONTROL, VIRTKEY
    VK_F1, 28817, NOINVERT, VIRTKEY
    VK_F2, 28690, NOINVERT, VIRTKEY
    VK_INSERT, 28697, NOINVERT, CONTROL, VIRTKEY
    VK_INSERT, 28698, NOINVERT, SHIFT, VIRTKEY
    VK_DELETE, 28689, NOINVERT, VIRTKEY
    VK_D, 28689, NOINVERT, CONTROL, VIRTKEY
    VK_DELETE, 28689, NOINVERT, SHIFT, VIRTKEY
    VK_RETURN, 28691, NOINVERT, ALT, VIRTKEY
    VK_1, 28749, CONTROL, SHIFT, VIRTKEY
    VK_2, 28751, CONTROL, SHIFT, VIRTKEY
    VK_3, 28750, CONTROL, SHIFT, VIRTKEY
    VK_4, 28752, CONTROL, SHIFT, VIRTKEY
    VK_5, 28753, CONTROL, SHIFT, VIRTKEY
    VK_6, 28747, CONTROL, SHIFT, VIRTKEY
    VK_7, 28748, CONTROL, SHIFT, VIRTKEY
    VK_8, 28754, CONTROL, SHIFT, VIRTKEY
    VK_ADD, 28759, ALT, CONTROL, VIRTKEY
    VK_SUBTRACT, 28760, ALT, CONTROL, VIRTKEY
    VK_OEM_PLUS, 28759, ALT, CONTROL, VIRTKEY
    VK_OEM_MINUS, 28760, ALT, CONTROL, VIRTKEY
}


3 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    ""s"", 34172, ALT
    VK_TAB, 41008, NOINVERT, VIRTKEY
    VK_TAB, 41008, NOINVERT, SHIFT, VIRTKEY
    VK_F5, 41504, NOINVERT, VIRTKEY
    VK_F6, 41008, NOINVERT, VIRTKEY
    VK_F3, 41093, NOINVERT, VIRTKEY
    VK_F4, 40964, NOINVERT, ALT, VIRTKEY
    VK_N, 40999, NOINVERT, CONTROL, SHIFT, VIRTKEY
}


4 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_F5, 1, NOINVERT, VIRTKEY
    VK_BACK, 2, NOINVERT, VIRTKEY
    VK_BACK, 3, NOINVERT, CONTROL, VIRTKEY
    VK_E, 40998, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_N, 40999, NOINVERT, CONTROL, SHIFT, VIRTKEY
}


5 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_X, 41025, NOINVERT, CONTROL, VIRTKEY
    VK_C, 41026, NOINVERT, CONTROL, VIRTKEY
    VK_V, 41027, NOINVERT, CONTROL, VIRTKEY
    VK_F2, 40996, NOINVERT, VIRTKEY
    VK_INSERT, 41026, NOINVERT, CONTROL, VIRTKEY
    VK_INSERT, 41027, NOINVERT, SHIFT, VIRTKEY
    VK_DELETE, 40995, NOINVERT, VIRTKEY
    VK_DELETE, 40995, NOINVERT, SHIFT, VIRTKEY
    VK_D, 40995, NOINVERT, CONTROL, VIRTKEY
    VK_RETURN, 40997, NOINVERT, ALT, VIRTKEY
    VK_F5, 41504, NOINVERT, VIRTKEY
}

"
#End Region

#End Region

#Region " notepad.exe.mui "

#Region " Windows 10 variants "

    ''' <summary>
    ''' Accelerator table definition for <c>notepad.exe.mui</c> with CRC32: 0a2fad88
    ''' </summary>
    Friend Const NOTEPAD_esES_ENGLISHIZED_0a2fad88 As String = "
LANGUAGE LANG_NEUTRAL, SUBLANG_NEUTRAL


GLOBALACC ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_N, 1, CONTROL, VIRTKEY
    VK_N, 8, CONTROL, SHIFT, VIRTKEY
    VK_O, 2, CONTROL, VIRTKEY
    VK_S, 3, CONTROL, VIRTKEY
    VK_S, 4, CONTROL, SHIFT, VIRTKEY
    VK_P, 6, CONTROL, VIRTKEY
    VK_W, 7, CONTROL, VIRTKEY
    VK_F1, 64, VIRTKEY
    VK_F3, 22, VIRTKEY
    VK_F3, 29, SHIFT, VIRTKEY
    VK_G, 24, CONTROL, VIRTKEY
    VK_F, 21, NOINVERT, CONTROL, VIRTKEY
    VK_H, 23, NOINVERT, CONTROL, VIRTKEY
    VK_E, 28, CONTROL, VIRTKEY
    VK_OEM_PLUS, 34, CONTROL, VIRTKEY
    VK_ADD, 34, CONTROL, VIRTKEY
    VK_OEM_MINUS, 35, CONTROL, VIRTKEY
    VK_SUBTRACT, 35, CONTROL, VIRTKEY
    VK_NUMPAD0, 36, CONTROL, VIRTKEY
    VK_0, 36, CONTROL, VIRTKEY
}


MAINACC ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_INSERT, 769, CONTROL, VIRTKEY
    VK_F5, 26, VIRTKEY
    VK_BACK, 16, ALT, VIRTKEY
    VK_Z, 16, CONTROL, VIRTKEY
    VK_X, 768, CONTROL, VIRTKEY
    VK_C, 769, CONTROL, VIRTKEY
    VK_V, 770, CONTROL, VIRTKEY
    VK_A, 25, CONTROL, VIRTKEY
}


SLIPUPACC ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_INSERT, 769, CONTROL, VIRTKEY
    VK_F5, 26, VIRTKEY
    VK_BACK, 16, ALT, VIRTKEY
    VK_Z, 16, CONTROL, VIRTKEY
    VK_X, 768, CONTROL, VIRTKEY
    VK_C, 769, CONTROL, VIRTKEY
    VK_V, 770, CONTROL, VIRTKEY
    VK_A, 25, CONTROL, VIRTKEY
    VK_ESCAPE, 7, VIRTKEY
    VK_C, 7, CONTROL, VIRTKEY
    VK_D, 7, CONTROL, VIRTKEY
    VK_Z, 7, CONTROL, VIRTKEY
}

"

    ''' <summary>
    ''' Accelerator table definition for <c>notepad.exe.mui</c> with CRC32: eb176603
    ''' </summary>
    Friend Const NOTEPAD_esES_ENGLISHIZED_eb176603 As String = "
LANGUAGE LANG_NEUTRAL, SUBLANG_NEUTRAL


GLOBALACC ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_N, 1, CONTROL, VIRTKEY
    VK_N, 8, CONTROL, SHIFT, VIRTKEY
    VK_O, 2, CONTROL, VIRTKEY
    VK_S, 3, CONTROL, VIRTKEY
    VK_S, 4, CONTROL, SHIFT, VIRTKEY
    VK_P, 6, CONTROL, VIRTKEY
    VK_W, 7, CONTROL, VIRTKEY
    VK_F1, 64, VIRTKEY
    VK_F3, 22, VIRTKEY
    VK_F3, 29, SHIFT, VIRTKEY
    VK_G, 24, CONTROL, VIRTKEY
    VK_F, 21, NOINVERT, CONTROL, VIRTKEY
    VK_H, 23, NOINVERT, CONTROL, VIRTKEY
    VK_E, 28, CONTROL, VIRTKEY
    VK_OEM_PLUS, 34, CONTROL, VIRTKEY
    VK_ADD, 34, CONTROL, VIRTKEY
    VK_OEM_MINUS, 35, CONTROL, VIRTKEY
    VK_SUBTRACT, 35, CONTROL, VIRTKEY
    VK_NUMPAD0, 36, CONTROL, VIRTKEY
    VK_0, 36, CONTROL, VIRTKEY
}


MAINACC ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_INSERT, 769, CONTROL, VIRTKEY
    VK_F5, 26, VIRTKEY
    VK_BACK, 16, ALT, VIRTKEY
    VK_Z, 16, CONTROL, VIRTKEY
    VK_X, 768, CONTROL, VIRTKEY
    VK_C, 769, CONTROL, VIRTKEY
    VK_V, 770, CONTROL, VIRTKEY
    VK_A, 25, CONTROL, VIRTKEY
}


SLIPUPACC ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_INSERT, 769, CONTROL, VIRTKEY
    VK_F5, 26, VIRTKEY
    VK_BACK, 16, ALT, VIRTKEY
    VK_Z, 16, CONTROL, VIRTKEY
    VK_X, 768, CONTROL, VIRTKEY
    VK_C, 769, CONTROL, VIRTKEY
    VK_V, 770, CONTROL, VIRTKEY
    VK_A, 25, CONTROL, VIRTKEY
    VK_ESCAPE, 7, VIRTKEY
    VK_C, 7, CONTROL, VIRTKEY
    VK_D, 7, CONTROL, VIRTKEY
    VK_Z, 7, CONTROL, VIRTKEY
}

"

#End Region

#Region " Windows 11 variants "

    ''' <summary>
    ''' Accelerator table definition for <c>notepad.exe.mui</c> with CRC32: 7a6b3ec1
    ''' </summary>
    Friend Const NOTEPAD_esES_ENGLISHIZED_7a6b3ec1 As String = "
LANGUAGE LANG_NEUTRAL, SUBLANG_NEUTRAL


GLOBALACC ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_N, 1, CONTROL, VIRTKEY
    VK_N, 8, CONTROL, SHIFT, VIRTKEY
    VK_O, 2, CONTROL, VIRTKEY
    VK_S, 3, CONTROL, VIRTKEY
    VK_S, 4, CONTROL, SHIFT, VIRTKEY
    VK_P, 6, CONTROL, VIRTKEY
    VK_W, 7, CONTROL, VIRTKEY
    VK_F1, 64, VIRTKEY
    VK_F3, 22, VIRTKEY
    VK_F3, 29, SHIFT, VIRTKEY
    VK_G, 24, CONTROL, VIRTKEY
    VK_F, 21, NOINVERT, CONTROL, VIRTKEY
    VK_H, 23, NOINVERT, CONTROL, VIRTKEY
    VK_E, 28, CONTROL, VIRTKEY
    VK_OEM_PLUS, 34, CONTROL, VIRTKEY
    VK_ADD, 34, CONTROL, VIRTKEY
    VK_OEM_MINUS, 35, CONTROL, VIRTKEY
    VK_SUBTRACT, 35, CONTROL, VIRTKEY
    VK_NUMPAD0, 36, CONTROL, VIRTKEY
    VK_0, 36, CONTROL, VIRTKEY
}


MAINACC ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_INSERT, 769, CONTROL, VIRTKEY
    VK_F5, 26, VIRTKEY
    VK_BACK, 16, ALT, VIRTKEY
    VK_Z, 16, CONTROL, VIRTKEY
    VK_X, 768, CONTROL, VIRTKEY
    VK_C, 769, CONTROL, VIRTKEY
    VK_V, 770, CONTROL, VIRTKEY
    VK_A, 25, CONTROL, VIRTKEY
}


SLIPUPACC ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_INSERT, 769, CONTROL, VIRTKEY
    VK_F5, 26, VIRTKEY
    VK_BACK, 16, ALT, VIRTKEY
    VK_Z, 16, CONTROL, VIRTKEY
    VK_X, 768, CONTROL, VIRTKEY
    VK_C, 769, CONTROL, VIRTKEY
    VK_V, 770, CONTROL, VIRTKEY
    VK_A, 25, CONTROL, VIRTKEY
    VK_ESCAPE, 7, VIRTKEY
    VK_C, 7, CONTROL, VIRTKEY
    VK_D, 7, CONTROL, VIRTKEY
    VK_Z, 7, CONTROL, VIRTKEY
}

"

#End Region

#End Region

#Region " wordpad.exe.mui "

#Region " Windows 10 variants "

    ''' <summary>
    ''' Accelerator table definition for <c>wordpad.exe.mui</c> with CRC32: 075f2d95
    ''' </summary>
    Friend Const WORDPAD_esES_ENGLISHIZED_075f2d95 As String = "
LANGUAGE LANG_NEUTRAL, SUBLANG_NEUTRAL


5 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_B, 32799, NOINVERT, CONTROL, VIRTKEY
    VK_B, 32799, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_C, 57634, NOINVERT, CONTROL, VIRTKEY
    VK_D, 32814, NOINVERT, CONTROL, VIRTKEY
    VK_E, 32804, NOINVERT, CONTROL, VIRTKEY
    VK_J, 32841, NOINVERT, CONTROL, VIRTKEY
    VK_F, 57636, NOINVERT, CONTROL, VIRTKEY
    VK_H, 57641, NOINVERT, CONTROL, VIRTKEY
    VK_I, 32800, NOINVERT, CONTROL, VIRTKEY
    VK_I, 32800, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_L, 32803, NOINVERT, CONTROL, VIRTKEY
    VK_M, 6306, NOINVERT, ALT, VIRTKEY
    VK_P, 57607, NOINVERT, CONTROL, VIRTKEY
    VK_R, 32805, NOINVERT, CONTROL, VIRTKEY
    VK_S, 57610, NOINVERT, CONTROL, VIRTKEY
    VK_U, 32802, NOINVERT, CONTROL, VIRTKEY
    VK_U, 32802, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_V, 57637, NOINVERT, CONTROL, VIRTKEY
    VK_BACK, 57643, NOINVERT, ALT, VIRTKEY
    VK_DELETE, 57635, NOINVERT, SHIFT, VIRTKEY
    VK_ESCAPE, 32768, NOINVERT, VIRTKEY
    VK_F1, 57669, NOINVERT, SHIFT, VIRTKEY
    VK_F3, 57640, NOINVERT, VIRTKEY
    VK_F6, 57680, NOINVERT, VIRTKEY
    VK_F6, 57681, NOINVERT, SHIFT, VIRTKEY
    VK_INSERT, 57634, NOINVERT, CONTROL, VIRTKEY
    VK_INSERT, 57637, NOINVERT, SHIFT, VIRTKEY
    VK_RETURN, 57860, NOINVERT, ALT, VIRTKEY
    VK_X, 57635, NOINVERT, CONTROL, VIRTKEY
    VK_Z, 57643, NOINVERT, CONTROL, VIRTKEY
    VK_1, 32806, NOINVERT, CONTROL, VIRTKEY
    VK_2, 32808, NOINVERT, CONTROL, VIRTKEY
    VK_5, 32807, NOINVERT, CONTROL, VIRTKEY
}


128 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_A, 57642, NOINVERT, CONTROL, VIRTKEY
    VK_B, 32799, NOINVERT, CONTROL, VIRTKEY
    VK_B, 32799, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_C, 57634, NOINVERT, CONTROL, VIRTKEY
    VK_D, 32814, NOINVERT, CONTROL, VIRTKEY
    VK_E, 32804, NOINVERT, CONTROL, VIRTKEY
    VK_J, 32841, NOINVERT, CONTROL, VIRTKEY
    VK_F, 57636, NOINVERT, CONTROL, VIRTKEY
    VK_H, 57641, NOINVERT, CONTROL, VIRTKEY
    VK_I, 32800, NOINVERT, CONTROL, VIRTKEY
    VK_I, 32800, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_L, 32803, NOINVERT, CONTROL, VIRTKEY
    VK_M, 6306, NOINVERT, ALT, VIRTKEY
    VK_N, 57600, NOINVERT, CONTROL, VIRTKEY
    VK_O, 57601, NOINVERT, CONTROL, VIRTKEY
    VK_P, 57607, NOINVERT, CONTROL, VIRTKEY
    VK_R, 32805, NOINVERT, CONTROL, VIRTKEY
    VK_S, 57603, NOINVERT, CONTROL, VIRTKEY
    VK_U, 32802, NOINVERT, CONTROL, VIRTKEY
    VK_U, 32802, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_V, 57637, NOINVERT, CONTROL, VIRTKEY
    VK_V, 57639, NOINVERT, ALT, CONTROL, VIRTKEY
    VK_BACK, 57643, NOINVERT, ALT, VIRTKEY
    VK_DELETE, 57635, NOINVERT, SHIFT, VIRTKEY
    VK_ESCAPE, 32768, NOINVERT, VIRTKEY
    VK_F1, 57669, NOINVERT, SHIFT, VIRTKEY
    VK_F3, 57640, NOINVERT, VIRTKEY
    VK_F6, 57680, NOINVERT, VIRTKEY
    VK_F6, 57681, NOINVERT, SHIFT, VIRTKEY
    VK_INSERT, 57634, NOINVERT, CONTROL, VIRTKEY
    VK_INSERT, 57637, NOINVERT, SHIFT, VIRTKEY
    VK_RETURN, 57860, NOINVERT, ALT, VIRTKEY
    VK_X, 57635, NOINVERT, CONTROL, VIRTKEY
    VK_Z, 57643, NOINVERT, CONTROL, VIRTKEY
    VK_1, 32806, NOINVERT, CONTROL, VIRTKEY
    VK_2, 32808, NOINVERT, CONTROL, VIRTKEY
    VK_5, 32807, NOINVERT, CONTROL, VIRTKEY
}

"

    ''' <summary>
    ''' Accelerator table definition for <c>wordpad.exe.mui</c> with CRC32: 12548387
    ''' </summary>
    Friend Const WORDPAD_esES_ENGLISHIZED_12548387 As String = "
LANGUAGE LANG_NEUTRAL, SUBLANG_NEUTRAL


5 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_B, 32799, NOINVERT, CONTROL, VIRTKEY
    VK_B, 32799, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_C, 57634, NOINVERT, CONTROL, VIRTKEY
    VK_D, 32814, NOINVERT, CONTROL, VIRTKEY
    VK_E, 32804, NOINVERT, CONTROL, VIRTKEY
    VK_J, 32841, NOINVERT, CONTROL, VIRTKEY
    VK_F, 57636, NOINVERT, CONTROL, VIRTKEY
    VK_H, 57641, NOINVERT, CONTROL, VIRTKEY
    VK_I, 32800, NOINVERT, CONTROL, VIRTKEY
    VK_I, 32800, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_L, 32803, NOINVERT, CONTROL, VIRTKEY
    VK_M, 6306, NOINVERT, ALT, VIRTKEY
    VK_P, 57607, NOINVERT, CONTROL, VIRTKEY
    VK_R, 32805, NOINVERT, CONTROL, VIRTKEY
    VK_S, 57610, NOINVERT, CONTROL, VIRTKEY
    VK_U, 32802, NOINVERT, CONTROL, VIRTKEY
    VK_U, 32802, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_V, 57637, NOINVERT, CONTROL, VIRTKEY
    VK_BACK, 57643, NOINVERT, ALT, VIRTKEY
    VK_DELETE, 57635, NOINVERT, SHIFT, VIRTKEY
    VK_ESCAPE, 32768, NOINVERT, VIRTKEY
    VK_F1, 57669, NOINVERT, SHIFT, VIRTKEY
    VK_F3, 57640, NOINVERT, VIRTKEY
    VK_F6, 57680, NOINVERT, VIRTKEY
    VK_F6, 57681, NOINVERT, SHIFT, VIRTKEY
    VK_INSERT, 57634, NOINVERT, CONTROL, VIRTKEY
    VK_INSERT, 57637, NOINVERT, SHIFT, VIRTKEY
    VK_RETURN, 57860, NOINVERT, ALT, VIRTKEY
    VK_X, 57635, NOINVERT, CONTROL, VIRTKEY
    VK_Z, 57643, NOINVERT, CONTROL, VIRTKEY
    VK_1, 32806, NOINVERT, CONTROL, VIRTKEY
    VK_2, 32808, NOINVERT, CONTROL, VIRTKEY
    VK_5, 32807, NOINVERT, CONTROL, VIRTKEY
}


128 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_A, 57642, NOINVERT, CONTROL, VIRTKEY
    VK_B, 32799, NOINVERT, CONTROL, VIRTKEY
    VK_B, 32799, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_C, 57634, NOINVERT, CONTROL, VIRTKEY
    VK_D, 32814, NOINVERT, CONTROL, VIRTKEY
    VK_E, 32804, NOINVERT, CONTROL, VIRTKEY
    VK_J, 32841, NOINVERT, CONTROL, VIRTKEY
    VK_F, 57636, NOINVERT, CONTROL, VIRTKEY
    VK_H, 57641, NOINVERT, CONTROL, VIRTKEY
    VK_I, 32800, NOINVERT, CONTROL, VIRTKEY
    VK_I, 32800, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_L, 32803, NOINVERT, CONTROL, VIRTKEY
    VK_M, 6306, NOINVERT, ALT, VIRTKEY
    VK_N, 57600, NOINVERT, CONTROL, VIRTKEY
    VK_O, 57601, NOINVERT, CONTROL, VIRTKEY
    VK_P, 57607, NOINVERT, CONTROL, VIRTKEY
    VK_R, 32805, NOINVERT, CONTROL, VIRTKEY
    VK_S, 57603, NOINVERT, CONTROL, VIRTKEY
    VK_U, 32802, NOINVERT, CONTROL, VIRTKEY
    VK_U, 32802, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_V, 57637, NOINVERT, CONTROL, VIRTKEY
    VK_V, 57639, NOINVERT, ALT, CONTROL, VIRTKEY
    VK_BACK, 57643, NOINVERT, ALT, VIRTKEY
    VK_DELETE, 57635, NOINVERT, SHIFT, VIRTKEY
    VK_ESCAPE, 32768, NOINVERT, VIRTKEY
    VK_F1, 57669, NOINVERT, SHIFT, VIRTKEY
    VK_F3, 57640, NOINVERT, VIRTKEY
    VK_F6, 57680, NOINVERT, VIRTKEY
    VK_F6, 57681, NOINVERT, SHIFT, VIRTKEY
    VK_INSERT, 57634, NOINVERT, CONTROL, VIRTKEY
    VK_INSERT, 57637, NOINVERT, SHIFT, VIRTKEY
    VK_RETURN, 57860, NOINVERT, ALT, VIRTKEY
    VK_X, 57635, NOINVERT, CONTROL, VIRTKEY
    VK_Z, 57643, NOINVERT, CONTROL, VIRTKEY
    VK_1, 32806, NOINVERT, CONTROL, VIRTKEY
    VK_2, 32808, NOINVERT, CONTROL, VIRTKEY
    VK_5, 32807, NOINVERT, CONTROL, VIRTKEY
}

"

#End Region

#Region " Windows 11 variants (https://winaero.com/wordpad-for-windows-11/) "

    ''' <summary>
    ''' Accelerator table definition for <c>wordpad.exe.mui</c> with CRC32: 845a4685
    ''' </summary>
    Friend Const WORDPAD_esES_ENGLISHIZED_845a4685 As String = "
LANGUAGE LANG_NEUTRAL, SUBLANG_NEUTRAL


5 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_B, 32799, NOINVERT, CONTROL, VIRTKEY
    VK_B, 32799, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_C, 57634, NOINVERT, CONTROL, VIRTKEY
    VK_E, 32804, NOINVERT, CONTROL, VIRTKEY
    VK_J, 32841, NOINVERT, CONTROL, VIRTKEY
    VK_F, 57636, NOINVERT, CONTROL, VIRTKEY
    VK_H, 57641, NOINVERT, CONTROL, VIRTKEY
    VK_I, 32800, NOINVERT, CONTROL, VIRTKEY
    VK_I, 32800, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_L, 32803, NOINVERT, CONTROL, VIRTKEY
    VK_M, 6306, NOINVERT, ALT, VIRTKEY
    VK_P, 57607, NOINVERT, CONTROL, VIRTKEY
    VK_R, 32805, NOINVERT, CONTROL, VIRTKEY
    VK_S, 57610, NOINVERT, CONTROL, VIRTKEY
    VK_U, 32802, NOINVERT, CONTROL, VIRTKEY
    VK_U, 32802, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_V, 57637, NOINVERT, CONTROL, VIRTKEY
    VK_BACK, 57643, NOINVERT, ALT, VIRTKEY
    VK_DELETE, 57635, NOINVERT, SHIFT, VIRTKEY
    VK_ESCAPE, 32768, NOINVERT, VIRTKEY
    VK_F1, 57669, NOINVERT, SHIFT, VIRTKEY
    VK_F3, 57640, NOINVERT, VIRTKEY
    VK_F6, 57680, NOINVERT, VIRTKEY
    VK_F6, 57681, NOINVERT, SHIFT, VIRTKEY
    VK_INSERT, 57634, NOINVERT, CONTROL, VIRTKEY
    VK_INSERT, 57637, NOINVERT, SHIFT, VIRTKEY
    VK_RETURN, 57860, NOINVERT, ALT, VIRTKEY
    VK_X, 57635, NOINVERT, CONTROL, VIRTKEY
    VK_Z, 57643, NOINVERT, CONTROL, VIRTKEY
    VK_1, 32806, NOINVERT, CONTROL, VIRTKEY
    VK_2, 32808, NOINVERT, CONTROL, VIRTKEY
    VK_5, 32807, NOINVERT, CONTROL, VIRTKEY
}


128 ACCELERATORS
LANGUAGE LANG_SPANISH, SUBLANG_SPANISH_MODERN
{
    VK_A, 57642, NOINVERT, CONTROL, VIRTKEY
    VK_B, 32799, NOINVERT, CONTROL, VIRTKEY
    VK_B, 32799, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_C, 57634, NOINVERT, CONTROL, VIRTKEY
    VK_E, 32804, NOINVERT, CONTROL, VIRTKEY
    VK_J, 32841, NOINVERT, CONTROL, VIRTKEY
    VK_F, 57636, NOINVERT, CONTROL, VIRTKEY
    VK_H, 57641, NOINVERT, CONTROL, VIRTKEY
    VK_I, 32800, NOINVERT, CONTROL, VIRTKEY
    VK_I, 32800, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_L, 32803, NOINVERT, CONTROL, VIRTKEY
    VK_M, 6306, NOINVERT, ALT, VIRTKEY
    VK_N, 57600, NOINVERT, CONTROL, VIRTKEY
    VK_O, 57601, NOINVERT, CONTROL, VIRTKEY
    VK_P, 57607, NOINVERT, CONTROL, VIRTKEY
    VK_R, 32805, NOINVERT, CONTROL, VIRTKEY
    VK_S, 57603, NOINVERT, CONTROL, VIRTKEY
    VK_U, 32802, NOINVERT, CONTROL, VIRTKEY
    VK_U, 32802, NOINVERT, CONTROL, SHIFT, VIRTKEY
    VK_V, 57637, NOINVERT, CONTROL, VIRTKEY
    VK_V, 57639, NOINVERT, ALT, CONTROL, VIRTKEY
    VK_BACK, 57643, NOINVERT, ALT, VIRTKEY
    VK_DELETE, 57635, NOINVERT, SHIFT, VIRTKEY
    VK_ESCAPE, 32768, NOINVERT, VIRTKEY
    VK_F1, 57669, NOINVERT, SHIFT, VIRTKEY
    VK_F3, 57640, NOINVERT, VIRTKEY
    VK_F6, 57680, NOINVERT, VIRTKEY
    VK_F6, 57681, NOINVERT, SHIFT, VIRTKEY
    VK_INSERT, 57634, NOINVERT, CONTROL, VIRTKEY
    VK_INSERT, 57637, NOINVERT, SHIFT, VIRTKEY
    VK_RETURN, 57860, NOINVERT, ALT, VIRTKEY
    VK_X, 57635, NOINVERT, CONTROL, VIRTKEY
    VK_Z, 57643, NOINVERT, CONTROL, VIRTKEY
    VK_1, 32806, NOINVERT, CONTROL, VIRTKEY
    VK_2, 32808, NOINVERT, CONTROL, VIRTKEY
    VK_5, 32807, NOINVERT, CONTROL, VIRTKEY
}

"

#End Region

#End Region

#End Region

End Module

#End Region